version: '3.8'
services:
  frontend-prod:
    container_name: rubik-prod-frontend
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
    ports:
      - '5001:80'
    depends_on:
      - backend-prod
    networks:
      - rubiks-network

  backend-prod:
    container_name: rubik-prod-backend
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend
    ports:
      - '5000:5000'
    networks:
      - rubiks-network

networks:
  rubiks-network:
    driver: bridge
