version: '3.8'
services:
  frontend-dev:
    container_name: rubik-dev-frontend
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
    ports:
      - '5002:80'
    depends_on:
      - backend-dev
    networks:
      - rubiks-dev-network

  backend-dev:
    container_name: rubik-dev-backend
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend
    ports:
      - '5000:5000'
    networks:
      - rubiks-dev-network

networks:
  rubiks-dev-network:
    driver: bridge
