version: '3.8'
services:
  frontend-dev:
    container_name: rubik-dev-frontend
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
    ports:
      - '5002:80'
    networks:
      - rubiks-dev-network

networks:
  rubiks-dev-network:
    driver: bridge
