FROM python:3.9-slim
WORKDIR /app
COPY backend/ .
RUN apt-get update && apt-get install -y \
    wget \
    gcc \
    libc-dev \
    && rm -rf /var/lib/apt/lists/* \
    && pip install gunicorn flask flask_cors kociemba \
    && rm -rf /root/.cache/pip \
    && apt-get purge -y --auto-remove gcc libc-dev
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "solve_server:app"]
EXPOSE 5000
